/******************************************************

   Class: AboutDialog.java
   purpose: Show some connectK information - e.g. version,auhor.
            This class is not really important.
   Author: Thuan Truong
   E-mail: tim@drimgmt.com

*******************************************************/
import java.awt.*;

import javax.swing.JPanel;

import symantec.itools.awt.ImagePanel;
//import com.sun.java.swing.JPanel;

public class AboutDialog extends Dialog {

	public AboutDialog(Frame parent, boolean modal)
	{
		super(parent, modal);

		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
        
		//{{INIT_CONTROLS
		setLayout(null);
		setBackground(new java.awt.Color(204,204,204));
		setSize(413,116);
		setVisible(false);
		label1.setText("Connect Version 2.0");
		add(label1);
		label1.setBounds(96,36,166,21);
		okButton.setLabel("OK");
		add(okButton);
		okButton.setBounds(288,48,66,27);
		label2.setText("Copyright (C) 1999-2002");
		add(label2);
		label2.setBounds(96,60,166,21);
		try {
			imageConnect.setImageURL(symantec.itools.net.RelativeURL.getURL("res/connect.gif"));
		}
		catch (java.net.MalformedURLException error) { }
		catch(java.beans.PropertyVetoException e) { }
		try {
			imageConnect.setStyle(symantec.itools.awt.ImagePanel.IMAGE_SCALED_TO_FIT);
		}
		catch(java.beans.PropertyVetoException e) { }
		imageConnect.setLayout(null);
		add(imageConnect);
		imageConnect.setBounds(24,36,48,48);
		JPanel1.setLayout(new FlowLayout(FlowLayout.CENTER,5,5));
		add(JPanel1);
		JPanel1.setBounds(252,36,20,40);
		label3.setText("Programmed by Thuan Truong");
		add(label3);
		label3.setBounds(96,84,180,24);
		setTitle("About Connect");
		//}}
        
		//{{REGISTER_LISTENERS
		SymWindow aSymWindow = new SymWindow();
		this.addWindowListener(aSymWindow);
		SymAction lSymAction = new SymAction();
		okButton.addActionListener(lSymAction);
		//}}

	}
    
	public AboutDialog(Frame parent, String title, boolean modal)
	{
		this(parent, modal);
		setTitle(title);
	}

	public void addNotify()
	{
		// Record the size of the window prior to calling parents addNotify.
                Dimension d = getSize();

		super.addNotify();

		// Only do this once.
		if (fComponentsAdjusted)
			return;

		// Adjust components according to the insets
		Insets insets = getInsets();
		setSize(insets.left + insets.right + d.width, insets.top + insets.bottom + d.height);
		Component components[] = getComponents();
		for (int i = 0; i < components.length; i++)
		{
			Point p = components[i].getLocation();
			p.translate(insets.left, insets.top);
			components[i].setLocation(p);
		}

		// Used for addNotify check.
		fComponentsAdjusted = true;
	}

	public void setVisible(boolean b)
	{
	    if (b)
	    {
    		Rectangle bounds = getParent().getBounds();
    		Rectangle abounds = getBounds();

    		setLocation(bounds.x + (bounds.width - abounds.width)/ 2,
    			 bounds.y + (bounds.height - abounds.height)/2);
	    }

		super.setVisible(b);
	}

	//{{DECLARE_CONTROLS
	java.awt.Label label1 = new java.awt.Label();
	java.awt.Button okButton = new java.awt.Button();
	java.awt.Label label2 = new java.awt.Label();
	symantec.itools.awt.ImagePanel imageConnect = new symantec.itools.awt.ImagePanel();
	JPanel JPanel1 = new JPanel();
	java.awt.Label label3 = new java.awt.Label();
	//}}
    
    // Used for addNotify check.
	boolean fComponentsAdjusted = false;

	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == okButton)
				okButton_ActionPerformed(event);
		}
	}

		void okButton_ActionPerformed(java.awt.event.ActionEvent event)
	{	 
		okButton_ActionPerformed_Interaction1(event);
	}


	void okButton_ActionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {
			this.dispose();
		} catch (Exception e) {
		}
	}


	class SymWindow extends java.awt.event.WindowAdapter
	{
		public void windowClosing(java.awt.event.WindowEvent event)
		{
			Object object = event.getSource();
			if (object == AboutDialog.this)
				AboutDialog_WindowClosing(event);
		}
	}

	void AboutDialog_WindowClosing(java.awt.event.WindowEvent event)
	{
		// to do: code goes here.
			 
		AboutDialog_WindowClosing_Interaction1(event);
	}


	void AboutDialog_WindowClosing_Interaction1(java.awt.event.WindowEvent event)
	{
		try {
			this.dispose();
		} catch (Exception e) {
		}
	}

}
